services:
  postgres:
    image: postgres:13
    container_name: flight-price-db
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-airflow}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-airflow}
      - POSTGRES_DB=${POSTGRES_DB:-airflow}
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data
    networks:
      - flight_network
    
  # Observability Stack
  dbgate:
    image: dbgate/dbgate
    restart: always
    ports:
      - "3000:3000"
    environment:
      - DB_USER=${POSTGRES_USER:-airflow}
      - DB_PASSWORD=${POSTGRES_PASSWORD:-airflow}
      - DB_HOST=${POSTGRES_HOST:-postgres}
      - DB_PORT=${POSTGRES_PORT:-5432}
      - DB_NAME=${POSTGRES_DB:-airflow}
    networks:
      - flight_network

volumes:
  postgres-db-volume:

networks:
  flight_network:
    external: true


